import type { Metadata, Viewport } from 'next'
import { Inter, Roboto } from 'next/font/google'
// import './globals.css'
import CssBaseline from '@mui/material/CssBaseline'
import Header from './components/Header'
import {Container} from "@mui/material";

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ weight: '300', subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width"/>
      </head>
      <body className={roboto.className}>
        <CssBaseline />
        <Header />
        <Container disableGutters>
            {children}
        </Container>
      </body>
    </html>
  )
}
